name: Build & Push Order Service Docker Image

on:
  push:
    branches: ['main']
  pull_request:
    branches: ['main']

env:
  IMAGE_NAME: order-service

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # 1. Checkout source
      - name: Checkout source
        uses: actions/checkout@v4

      # 2. Setup Java 21 (JHipster 8 d√πng 21)
      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 21
          cache: maven

      # 3. Build Spring Boot
      - name: Build with Maven
        run: ./mvnw -B -DskipTests package

      # 4. Login Docker Hub
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      # 5. Build Docker image
      - name: Build Docker image
        run: |
          docker build -t ${{ secrets.DOCKER_USERNAME }}/${{ env.IMAGE_NAME }}:latest .

      # 6. Push Docker image
      - name: Push Docker image
        run: |
          docker push ${{ secrets.DOCKER_USERNAME }}/${{ env.IMAGE_NAME }}:latest
